sample: "sample"
fastq_r1: "data/SRR15334628_1.fastq"
fastq_r2: "data/SRR15334628_2.fastq"
enable_variant_calling: true
reference_fasta: "data/refgenome/ecoli_INF32-16-A_ref.fasta"
# Optional: provide SHA256 of reference_fasta to verify integrity (empty to skip)
reference_sha256: ""
aligner: "bowtie2"      # options: bwa, bowtie2
mark_duplicates: false   # if true, use mkdup BAM for calling
caller: "bcftools"       # currently supported: bcftools
ploidy: 1                # bacteria default

# Variant filtering thresholds (bcftools filter)
# Records failing the expression are excluded. Defaults match previous hardcoded values.
filter_min_qual: 20      # minimum QUAL
filter_min_dp: 5         # minimum depth (DP)

# fastp configuration (optional). Extra args appended to the fastp command.
# Example: "--trim_front1 5 --trim_front2 5 --length_required 50"
fastp_extra_args: ""

# Optional species identification (Mash)
species_id_enabled: true
species_refs_dir: "data/species_refs"  # directory with small set of reference FASTAs (*.fa|*.fna|*.fasta)

# Optional resistance annotation (requires BED on the same reference)
resistance_annotation_enabled: true
resistance_genes_bed: "data/resistance_genes.bed"
resistance_genes_bed_sha256: ""

# Optional variant effect annotation (SnpEff)
snpeff_enabled: false
# When using a prebuilt SnpEff genome, set snpeff_genome (e.g., 'Escherichia_coli_K12').
# For custom annotation against your reference, set snpeff_genome (e.g., 'custom') and provide snpeff_gff.
snpeff_genome: "custom"
# Directory where SnpEff stores databases and genomes (written by the pipeline)
snpeff_data_dir: "results/snpeff"
# GFF3 annotation file matching your reference (required for custom DB builds). Leave empty to skip DB build.
snpeff_gff: ""
